### ISSUE TITLE
Jest Testing

### ISSUE THREAD

**Issue by n-aggarwal** [n-aggarwal/comp-333-5#13]
@ananafrida I get the following errors when I try to run the tests:

npm install

up to date, audited 1579 packages in 2s

254 packages are looking for funding
run npm fund for details

9 vulnerabilities (3 moderate, 6 high)

To address issues that do not require attention, run:
npm audit fix

To address all issues (including breaking changes), run:
npm audit fix --force

Run npm audit for details.
npm run test

initial@0.1.0 test
react-scripts test
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
Usually this happens when watchman isn't running. Create an empty .watchmanconfig file in your project's root folder or initialize a git or hg repository in your project.
Error: Watchman error: std::__1::system_error: open: /Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/src: Operation not permitted. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
node:events:497
throw er; // Unhandled 'error' event
^

Error: std::__1::system_error: open: /Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/src: Operation not permitted
at BunserBuf. (/Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/node_modules/fb-watchman/index.js:99:23)
at BunserBuf.emit (node:events:519:28)
at BunserBuf.process (/Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/node_modules/bser/index.js:292:10)
at /Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/node_modules/bser/index.js:247:12
at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Emitted 'error' event on WatchmanWatcher instance at:
at Client. (/Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/node_modules/jest-haste-map/build/watchers/WatchmanWatcher.js:150:10)
at Client.emit (node:events:519:28)
at BunserBuf. (/Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/node_modules/fb-watchman/index.js:111:12)
at BunserBuf.emit (node:events:519:28)
at /Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/node_modules/bser/index.js:249:12
at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
watchmanResponse: {
error: 'std::__1::system_error: open: /Users/nishantaggarwal/Documents/git-repositories/comp-333-3-frontend/src: Operation not permitted',
version: '2023.09.25.00'
}
}

Node.js v21.2.0

Could you please fix them ASAP.

**Comment by n-aggarwal** [comment]
Thanks for the info @ananafrida. I was able to fix the issue. It was a "watchman" permissions issue. I will update the readme with the troubleshooting tips.
